### ISSUE TITLE
Dynamic update of list of table sources

### ISSUE THREAD

**Issue by rishabhjain30** [maplibre/martin#12]
Is there a way to generate vector tiles from tables that are added to the DB after starting Martin?

On a separate note, the project looks great. Thanks.

**Comment by stepankuzmin** [comment]
Hi there, @rishabhjain30! Yes, it's planned in the future releases. Will keep this issue until it's ready.

**Comment by YLagh01** [comment]
Hello

I'm sorry for re-intervening on such an old post but I would also like to do what's on the title. I can't find a way to do it in the documentation or in other issues. As this issue has apparently been solved, would somebody tell me how to do that?

Thank you very much!

**Comment by CommanderStorm** [comment]
Sorry, we should have updated this issue when the feature was [yanked in `v0.6`](https://github.com/maplibre/martin/releases/tag/v0.6.0).
This is not supported currently, but might in the future.

- https://github.com/maplibre/martin/issues/288

I have started our second run at implementation in the following PR, but this is not quite done yet.

- https://github.com/maplibre/martin/pull/1585

Currently, you will need to restart martin to update its state, which is unfortunate.

**Comment by YLagh01** [comment]
@CommanderStorm I understand, thank you for the quick answer and good luck implementing the feature!
