### ISSUE TITLE
Database user and password

### ISSUE THREAD

**Issue by digitaltopo** [maplibre/martin#14]
How do we specify user and password for database connections?

**Comment by minikarma** [comment]
starting Martin you have to specify connection string
`martin postgres://postgres@localhost/db`

**Comment by stepankuzmin** [comment]
Hey @digitaltopo! You should use a libpq connection URI as in [documentation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING).

```
postgresql://[user[:password]@][netloc][:port][,...][/dbname][?param1=value1&...]
```

Eg. 

```shell
martin postgres://user:password@host/dbname
```
