### ISSUE TITLE
How fast is the real-time loading speed?

### ISSUE THREAD

**Issue by yh371174229** [maplibre/martin#15]
I have a mount of data(about >=5 million,Up to 100 million).And the area polygon has many points,now I use **tilestrata + postgresql** to rendering geo data ,but only can zoom to 13level and the speed is not ideal.，I want to know whether martin can solve my problem（real time rendering  big geo data）

Forgive my poor English level，hope  you can understand me。
Any Help will appreciated！

**Comment by stepankuzmin** [comment]
Hi @yh371174229! I didn't benchmark marting with tilestrata yet. If you use [tilestrata-postgismvt](https://github.com/Stezii/tilestrata-postgismvt) the speed may be about the same as both martin and tilestrata utilizes PostGIS `ST_AsMVT` function for generating tiles. 

I'm closing the issue for now, maybe I'll run some benchmarks later.
