### ISSUE TITLE
Attribution is null

### ISSUE THREAD

**Issue by maxammann** [maplibre/martin#151]
I just setup martin and in MapboxGL JS everything is fine. Mapbox GL on Android has a problem with the TileJSON though as the "attribution" field is null.

There is an error log on Android which says:
```
Failed to load source xyz: source attribution must be a string
```

When using the XYZ tile url directly without using TileJSON Mapbox gl is happy. 

Should it be possible to configure these fields?

**Comment by unusorin** [comment]
For example this causes issues with tileserver-gl. Because the attribution is null, it would not render the raster version of the style. Workaround was to use xyz scheme directly and skip the manifest.
