### ISSUE TITLE
Docker image versioning for improved stability

### ISSUE THREAD

**Issue by yamaszone** [maplibre/martin#171]
@stepankuzmin would you please consider pushing versioned container using git release tag such as “martin:0.5.0” to allow users pin down version and to avoid forcing upgrades silently (and potentially break app)? Also, can you please release a new tag from mainline branch since it has newer changes than release 0.5.0?

Thanks in advance for sharing such a powerful app!

**Comment by yamaszone** [comment]
Actually the Docker Hub repo already contains tag for `0.5.0`. Disregard my first part of the comment. Also, can you please release a new tag from mainline branch since it has newer changes than release 0.5.0?

**Comment by stepankuzmin** [comment]
Hey @yamaszone 

I'll release new version after #107

**Comment by yamaszone** [comment]
@stepankuzmin Sounds great! Thanks again!
