### ISSUE TITLE
question: Does it support raster data?

### ISSUE THREAD

**Issue by EverWinter23** [maplibre/martin#18]
Can we store/map raster data using `postgis + martin` to speed up rendering on the client side?

**Edit:** And if it does not, how can that be achieved?

**Comment by stepankuzmin** [comment]
Hi! Currently, martin doesn't support raster tiles, but it can be added in the feature releases.

**Comment by Baschdl** [comment]
@stepankuzmin Did you already think about how one could implement this? Resorting to mapnik etc. for rendering and just serving the resulting raster tiles?

**Comment by EverWinter23** [comment]
@Baschdl Maybe this helps?

Take a look at `mbtiles` format. Use GDAL's `gdal2mbtiles` to tile the `GeoTiff` [raster source] and then use [mbtile-server](https://github.com/consbio/mbtileserver) to serve them to the frontend which can be consumed by `mapbox`, `OSM` etc.
