### ISSUE TITLE
Setup a minimun zoom in config file

### ISSUE THREAD

**Issue by phpia** [maplibre/martin#206]
It would be nice if it will be possible to limit the minimum zoom at wich martin return tiles.

I know that Im able to do it from javascript in leaflet or mapbox but anyone is able to bypass this control and could perform like dddos attak against postgres 

Thanks!

**Comment by douglasg14b** [comment]
This would be very good to have. Though a workaround for now could be to prevent such requests from your reverse proxy? NGINX for example can use regex patterns.
