### ISSUE TITLE
Recent pull request broke parameter passing via json

### ISSUE THREAD

**Issue by saosebastiao** [maplibre/martin#223]
I have the following function:
```
CREATE OR REPLACE FUNCTION v2.license_geometries(z integer, x integer, y integer, query_params json) RETURNS bytea AS $$
DECLARE
    mvt bytea;
BEGIN
    RAISE NOTICE 'params: %',query_params;
    WITH tile AS (
        SELECT distinct
            geom_id,
            ST_AsMVTGeom(ST_Transform(geom, 3857), TileBBox(z, x, y, 3857), 4096, 64, true) AS geom
        FROM v2.license_geometries g
        INNER JOIN v2.license_metadata m
            USING (geom_id)
        WHERE geom && TileBBox(z, x, y, 4326)
            AND call_sign = (query_params->>'call_sign')::varchar
    )
    SELECT INTO mvt ST_AsMVT(t.*, 'v2.license_geometries', 4096, 'geom')
    FROM tile t;
    RETURN mvt;
END
$$
LANGUAGE plpgsql
IMMUTABLE STRICT
PARALLEL SAFE;
```
Before this [recent pull request](https://github.com/urbica/martin/pull/216), the martin endpoint would return correctly, but now it will not. 

I've traced it down to the json object being escaped somehow. 

When I call it manually in a postgres console: `select v2.license_geometries(7,34,48,'{"call_sign":"WMH528"}');` the debug notice shows: `params: {"call_sign":"WMH528"}`.

However, when martin calls this endpoint: `/rpc/v2.license_geometries/7/34/48.pbf?call_sign=WMH528`, I get this for the notice: `... postgres::config] NOTICE: params: "{\"call_sign\":\"WMH528\"}"`

It appears that the previous version passed in a json object as the fourth parameter, but the latest version passes in a stringified version of the json object, which breaks all json parsing behavior within the function. It's not clear to me if that is intended behavior or not (the PR mentions it addresses potential SQL injection), but if it is, I would think it would be a semver major version bump and a docs change. 

Let me know if you can't replicate (it's hard to clone our database for replication purposes, but the function could be rewritten for debugging this specific issue).

**Comment by frodrigo** [comment]
Before and after it was a string, but now it is escaped:
https://github.com/urbica/martin/pull/216/files#diff-4846e58a734905ebf0390dc19a28478889648aa4d29cc74759bbb814dae6cc3e

`'{"call_sign":"WMH528"}'` and `"{\"call_sign\":\"WMH528\"}"`, but the first with simple quote and not the last.

**Comment by gbip** [comment]
> It appears that the previous version passed in a json object as the fourth parameter, but the latest version passes in a stringified version of the json object, which breaks all json parsing behavior within the function. It's not clear to me if that is intended behavior or not (the PR mentions it addresses potential SQL injection), but if it is, I would think it would be a semver major version bump and a docs change.

Hey, I'm the author of #216 which breaks martin for you.
Passing json directly from the url params to the SQL allows someone malicious to break your database by injecting malicious SQL queries. If your martin inputs are only from trusted clients you could roll back to the previous versions.

As for why the PR break this feature, I'm not sure. It uses prepared SQL queries to avoid SQL injection. Such queries should not have a different behaviour standard queries, so this needs a little bit of investigation.

**Comment by frodrigo** [comment]
Ok. I got your point, I have the same issue. The content of `query_params` is now a dumped json in a string, and not directly a json.
