### ISSUE TITLE
Support for Nginx Reverse proxy to support base url and domain name

### ISSUE THREAD

**Issue by shaunakv1** [maplibre/martin#30]
Hi!

First up, thank you for your awesome work on this project! I have evaluated all the alternatives out there for vector tile server and this is the best one that works out of box!

We plan on running martin behind a reverse proxy. This works fine, but martin currently does not support  `base url` and `domain names`.

For example:  We want to reverse proxy **example.com/tileserver/** to martin server. 
Now while this works, martin does not adjust the URLs that are output in the json responses to reflect the base path `tileserver` and the domain `example.com`.  The json responses still say that the endpoints are `localhost:3000/something.json`. 

Support for configuration is required so that the json data will reflect the `example.com/tileserver/<something>.json`

This is potentially solve able by adding support for environment variables like :  `DOMAIN_NAME` `BASE_URL` which updates the source table json end points to reflect the correct urls. 

Hope my point is clear, but please let me know if you need more details!

**Comment by shaunakv1** [comment]
Sorry just noticed that this is already documented in the readme. Closing

**Comment by Danysan1** [comment]
In case anyone else stumbles upon on this problem, the documentation for using a reverse proxy has been moved to https://maplibre.org/martin/24-run-with-nginx.html#rewriting-urls

**Comment by nyurik** [comment]
@Danysan1 thx, did you see an old link anywhere?  I would like it fix it if possible

**Comment by Danysan1** [comment]
No, there is no broken link, but the previous comment referenced the readme and there isn't anything (anymore) about using a reverse proxy in the readme

**Comment by nyurik** [comment]
ah yes, thx.  We are trying to reduce the size of README - it became a bit unmanageable - so most of the info is now in the doc book.
