### ISSUE TITLE
Can't generate config: database error

### ISSUE THREAD

**Issue by rafaelfernandezgis** [maplibre/martin#38]
Hi there,
I was just playing a little with Urbica/Martin trying to serve MVTs from my postgis image.
I ran your 'docker run --net=host -p 3000:3000 -e DATABASE_URL=postgres://postgres:postgres@localhost/postgres urbica/martin'

However I got:
[2019-11-05T12:45:11Z INFO  martin] Starting martin v0.5.0
[2019-11-05T12:45:11Z INFO  martin] Config is not set, scanning database
[2019-11-05T12:45:11Z INFO  martin] Connected to postgres://postgres:postgres@localhost/postgres
[2019-11-05T12:45:11Z ERROR martin] Can't generate config: database error

Any clue about the source of this error?

Thx!
Rafael

**Comment by stepankuzmin** [comment]
Hi @rafaelfernandezgis! Thanks for filling this issue.

Could you please run martin in [debug mode](https://github.com/urbica/martin#debugging)?

```shell
docker run \
  --net=host \
  -p 3000:3000 \
  -e DATABASE_URL=postgres://postgres:postgres@localhost/postgres \
  -e RUST_LOG=actix_web=info,martin=debug,postgres=debug \
  urbica/martin
```

**Comment by rafaelfernandezgis** [comment]
Hi @stepankuzmin,
I ran martin in debug mode and I found that I had created my table without a valid geom field. So...my bad sorry.
Now it's running like a champ.
Thanks a lot! :+1:
