### ISSUE TITLE
martin config expose only specific schema

### ISSUE THREAD

**Issue by Captain-Oski** [maplibre/martin#47]
Hello ! Thank you for the superbe work ! 

I am wondering if we could expose only a entire schema instead of exposing one table at a time ?

Thank you

**Comment by stepankuzmin** [comment]
Hi @Captain-Oski! Thanks for the idea, but I'm not sure how do you want it to be. Could you please provide an example for this?

**Comment by Captain-Oski** [comment]
Thank you for replying so quickly : 

it could be something like this alongside the config.yaml: 

```
schema_sources:
  public
  mySchema
  myOtherSchema
```

So that it would only targets all the tables and functions into a specific schema.

I founding it extremely verbose and difficult to maintain an config file when you need multiple tables and functions but need to hide from the public numerous tables. 

I guess one could migrate the needed tables and functions into a new database instance but ...

**Comment by stepankuzmin** [comment]
I see the problem with config verbosity, but schema sources don't fit very well yet. I'll think about how to simplify config to expose schemas, thanks!

**Comment by nyurik** [comment]
The #380 makes this possible, but would require us to think how to add it to configuration

**Comment by nyurik** [comment]
Implemented in #510, pending a few more PR megres

**Comment by nyurik** [comment]
@stepankuzmin and I at the last minute realized that we don't have a clear agreement on how to specify schema configuration list for this feature.  See #512 -- can use your feedback on the best way to configure, as well as possible usecases you can think of

**Comment by nyurik** [comment]
added in #546
