### ISSUE TITLE
Allow on-disk caching of tiles

### ISSUE THREAD

**Issue by MathiasVersichele** [maplibre/martin#54]
Any plans on allowing on-disk caching of tiles ?

So basically:
```
if(!tile_on_disk.exists) {
  run_sql
  save_to_disk
  return tile
}
else {
  return tile_on_disk
}
```

**Comment by stepankuzmin** [comment]
Hi @MathiasVersichele! I'm not planning to support tiles cache as there are already some solutions such as Nginx etc. What is your use case for that?

**Comment by MathiasVersichele** [comment]
Hi @stepankuzmin, I understand. I've written a simple http server which does what I want. Thanks for the great work !

**Comment by manhcuongincusar1** [comment]
hello @stepankuzmin : i am new in programing, can you give a guide for configing caching and http-proxy.
thanks alot
