### ISSUE TITLE
can not parse "{z}" to a u32

### ISSUE THREAD

**Issue by diouck** [maplibre/martin#59]
Hello I just installed in manual mode Martin. But I have this error:

```
http://185.216.25.216:3000/public.perimeters/{z}/{x}/{y}.pbf
can not parse "{z}" to a u32
```

Do you have any idea what is blocking. Thank you

**Comment by stepankuzmin** [comment]
Hi @diouck 

Could you please provide request URLs that cause this error?

**Comment by diouck** [comment]
docker run -p 3000:3000 -e DATABASE_URL=postgres://postgres@localhost/carto urbica/martin

I have this error with mapbox `ajax.js:81 GET http://185.216.25.216:3000/public.perimeters/%7Bz%7D/%7Bx%7D/%7By%7D.pbf 404 (Not Found)`

**Comment by stepankuzmin** [comment]
There should be [slippy map tilenames](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) instead of `{z}/{x}/{y}` in your request. What mapping library do you use for displaying a map?

**Comment by diouck** [comment]
I use MapboxGl
`map.addLayer({
  id: 'public.perimeters',
  type: 'fill',
  source: {
    type: 'vector',
    url: 'http://185.216.25.216:3000/public.perimeters/{z}/{x}/{y}.pbf'
  },
  'source-layer': 'public.perimeters'
});
`

**Comment by stepankuzmin** [comment]
You should use `TileJSON` endpoint for the `url` param in the source, [here is an example](https://github.com/urbica/martin#using-with-mapbox-gl-js).

**Comment by diouck** [comment]
Thank you very much, it's perfect. But I just have one last question. How to generate the cache? And where can we access it?
Thank you

**Comment by stepankuzmin** [comment]
Martin doesn't have built-in cache support, so it's up to you. If you are using some kind of reverse proxy (e.g. Nginx), you can setup caching there. Or you can also iterate over tiles in your region and simply download it to a disk.
