### ISSUE TITLE
filtering a layer before tiles are created

### ISSUE THREAD

**Issue by EarthAdam** [maplibre/martin#60]
If I would like to filter a large layer based on feature properties, is that something I can do before creating a vectorTile for the entire layer, or do I have to rely on the Mapbox JS filter once the entire layer is loaded?

**Comment by stepankuzmin** [comment]
Hey @OhioAdam! You can use [Function Sources](https://github.com/urbica/martin#function-sources) for that. Function Source is a database function that can be used to build vector tiles. You can also use request query params to filter features based on their properties.
