### ISSUE TITLE
how to set up vector tiles caching with nginx?

### ISSUE THREAD

**Issue by manhcuongincusar1** [maplibre/martin#75]
hello guys! I am new with both gis and nginx. 
I have try a lot with caching vector tiles throut Nginx with Martin. like that! But it didn't work, my /var/cache/ngix folder still empty.
can any body give me a tutorial to cache and reserve proxy with nginx. Thanks in seriously

[nginx.conf.zip](https://github.com/urbica/martin/files/4460090/nginx.conf.zip)

**Comment by stepankuzmin** [comment]
Hi! You may ask this question on Stackoverflow with the `Nginx` tag.

**Comment by manhcuongincusar1** [comment]
thanks

**Comment by stepankuzmin** [comment]
Hi @manhcuongincusar1 

I've added a note on caching with Nginx to the docs https://github.com/urbica/martin#caching-tiles
