### ISSUE TITLE
how to stop simplify geometry?

### ISSUE THREAD

**Issue by manhcuongincusar1** [maplibre/martin#76]
first, thanks for making Martin. it is simple and flexible. 
i have a question: how to config simplifing geometry? -

thanks in advance

**Comment by stepankuzmin** [comment]
Hi! You can write your own [Function Source](https://github.com/urbica/martin#function-sources) and use [`ST_Simplify`](https://postgis.net/docs/ST_Simplify.html) or [`ST_SimplifyPreserveTopology`](ST_SimplifyPreserveTopology) to simplify geometry.

**Comment by manhcuongincusar1** [comment]
can prevent simplify?
