### ISSUE TITLE
Can I mix config.yml and environment vars?

### ISSUE THREAD

**Issue by edtjones** [maplibre/martin#93]
Hi folks

Thanks for an excellent piece of software :)

I would like to deploy Martin with specific tables and functions available. I can do this with config.yaml just fine. But if I use the `--config=config.yaml` option when starting `martin`, the YAML is required to have a `connection_string` key. I'm hosting on Heroku, which only has $DATABASE_URL available as an environment variable.

Is it possible to interpolate environment variables in the config file? Or can I set the `connection_string` key in the config file to some value to tell `martin` to use the environment variable?

Thanks

**Comment by edtjones** [comment]
Sorry, I should have said that my workaround at the moment is to exclude `connection_string` and `listen_addresses` from my template `config.yml` and import them in an entrypoint.sh, like this:

Dockerfile:
```
FROM urbica/martin
RUN mkdir -p /app/config
COPY config/config.yaml /app/config/config.yaml

WORKDIR /app
ENTRYPOINT /app/config/docker/entrypoint.sh $DATABASE_URL $PORT
```

Entrypoint.sh:
```
#!/bin/sh

set -e

config='/app/config/config.yaml'
sed -i '/^connection_string:.*/d' $config
sed -i '/^listen_addresses:.*/d' $config
echo connection_string: $1 >> $config
echo listen_addresses: "0.0.0.0:$2" >> $config

martin --config /app/config/config.yaml
```

**Comment by stepankuzmin** [comment]
Hi @edtjones! Currently, there is no support for both config and environment variables out of the box. I think you can try to use some kind of `envsubst` in your entry point script as a workaround for now.

**Comment by edtjones** [comment]
No worries @stepankuzmin I got a slight variation of the scripts above working ok on Heroku. Here they are for reference / others who might find them useful:

Dockerfile:
```
FROM urbica/martin
RUN apk add curl
RUN mkdir -p /app/config
COPY config.yaml /app/config/docker/config.yaml
COPY entrypoint.sh /app/config/docker/entrypoint.sh

WORKDIR /app
ENTRYPOINT /app/config/docker/entrypoint.sh
```

entrypoint.sh

```
#!/bin/sh

set -e

config='/app/config/docker/config.yaml'
sed -i '/^connection_string:.*/d' $config
sed -i '/^listen_addresses:.*/d' $config
echo connection_string: $DATABASE_URL >> $config
echo listen_addresses: "0.0.0.0:$PORT" >> $config

martin --config /app/config/docker/config.yaml
```

These overwrite the `connection_string` and `listen_addresses` lines in the config.yaml with the contents of the `$DATABASE_URL` and `$PORT` environment variables (at runtime), which works fine.
